services:
  php-apache-environment:
    container_name: php-apache-authenticationApp
    build:
      context: ./phpDir
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./phpDir/src:/var/www/html/
    ports:
      - 8005:80

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nimda
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: nimda
